# Generated by Django 4.2.29 on 2026-09-17 09:10

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_footer_text',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='Text that will appear in the footer of this journal.', null=True, verbose_name='Journal footer text'),
        ),
    ]
